Always return counters and counter_values
Always return two hashes from perf_capture_metrics because the calling
method expects it.

Catching an exception and logging the error without returning the proper
values leads to:
```
[NoMethodError]: undefined method `[]' for true:TrueClass
```

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1744845