Remove require_nested :Runner where it's not implemented (yet)
Presence of these requires would lead to the following error when
doing rake gettext:store_model_attributes

LoadError: No such file to load --
manageiq/providers/azure/network_manager/event_catcher/runner
lib/extensions/require_nested.rb:11:in `require_nested'
app/models/manageiq/providers/azure/network_manager/event_catcher.rb:2:in
`<class:EventCatcher>'
app/models/manageiq/providers/azure/network_manager/event_catcher.rb:1:in
`<top (required)>'

(transferred from ManageIQ/manageiq@9463103ebd7c5af9c201252ae77e097172b71e3d)